# Travis continuous integration system configuration file.
# Read more at: http://docs.travis-ci.com/user/customizing-the-build/

sudo: required
dist: xenial
language: node_js
node_js: 11.6.0

git:
  depth: 500
  quiet: true

cache:
  directories:
    - .cached_tools
    - ~/.cache
    - node_modules

before_install:
  - export NG_CLI_ANALYTICS=ci
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - export GO111MODULE=on
  - export GOPROXY=https://proxy.golang.org
  - export PATH=$PATH:$GOPATH/bin
  - eval "$(gimme 1.12.6)"

before_script:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce libgconf2-4
  - sudo service docker restart
  - docker --version

jobs:
  include:
    - stage: test
      name: "Test"
      before_script:
        - aio/scripts/install-codegen.sh
      script: npm run check
    - name: "Test coverage"
      script: npm run test:coverage
      after_success:
        - rm -rf $TRAVIS_BUILD_DIR/.tmp
        - bash <(curl -s https://codecov.io/bash)
    - name: "Helm linting"
      install:
        - curl -L https://git.io/get_helm.sh | bash && helm init --skip-refresh --client-only
      before_script: skip
      script:
        - cd aio/deploy/helm-chart/kubernetes-dashboard
        - helm lint
        - helm template .
    - name: "e2e tests"
      script: npm run cluster:start && npm run e2e

    - stage: deploy
      name: "docker push head"
      script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        - npm run docker:push:head

    - stage: release
      name: "Docker push"
      script:
        - docker login -u $DOCKER_RELEASE_USER -p $DOCKER_RELEASE_PASS
        - npm run docker:push
    - name: "Helm repository generation"
      before_script:
        - curl -L https://git.io/get_helm.sh | bash && helm init --skip-refresh --client-only
      script:
        - helm package "aio/deploy/helm-chart/kubernetes-dashboard"
        - git fetch
        - git checkout gh-pages
        - helm repo index .
        # Push using a GitHub deploy key encrypted by travis
        # GitHub deploy key: see https://developer.github.com/v3/guides/managing-deploy-keys/#deploy-keys
        # Travis encryption: See https://docs.travis-ci.com/user/encrypting-files/#automated-encryption
        - openssl aes-256-cbc -K $encrypted_dc4c0df7bb33_key -iv $encrypted_dc4c0df7bb33_iv -in id_rsa_bot.enc -out id_rsa_bot -d
        - eval "$(ssh-agent -s)"
        - chmod 600 id_ed25519
        - ssh-add id_rsa_bot
        - git add --all :/ && git commit -m "Update Helm repository from CI."
        - git push "git@github.com:${TRAVIS_REPO_SLUG}.git" origin gh-pages

stages:
  - test
  - name: deploy
    if: branch = master AND type != pull_request
  - name: release
    if: tag IS present AND type != pull_request
